/** Everything the user configures about the robot. Persisted with the file. */
export type RobotConstants = {
    holonomicRobot: boolean,
    width: number,
    height: number,
    speed: number,
    trackwidth: number,
    lateralTau: number,  // first-order lag time constant for lateral (linear) motion (seconds)
    angularTau: number,  // first-order lag time constant for angular (turning) motion (seconds)
    cogOffsetX: number, // lateral offset (positive = robot's right)
    cogOffsetY: number, // longitudinal offset (positive = robot's forward)
    cogOffsetXDisabled: boolean,
    cogOffsetYDisabled: boolean,
    expansionFront: number,
    expansionLeft: number,
    expansionRight: number,
    expansionRear: number,
    expansionFrontDisabled: boolean,
    expansionLeftDisabled: boolean,
    expansionRightDisabled: boolean,
    expansionRearDisabled: boolean,
    sensorFrontX: number,
    sensorFrontY: number,
    sensorFrontDisabled: boolean,
    sensorLeftX: number,
    sensorLeftY: number,
    sensorLeftDisabled: boolean,
    sensorRightX: number,
    sensorRightY: number,
    sensorRightDisabled: boolean,
    sensorRearX: number,
    sensorRearY: number,
    sensorRearDisabled: boolean,
    updateHz: number,
    latencyMs: number,
    latencyDisabled: boolean,
}

export const defaultRobotConstants: RobotConstants = {
    holonomicRobot: false,
    width: 14,
    height: 14,
    speed: 6,
    trackwidth: 12,
    lateralTau: 0.2,
    angularTau: 0.1,
    cogOffsetX: 0,
    cogOffsetY: 0,
    cogOffsetXDisabled: true,
    cogOffsetYDisabled: true,
    expansionFront: 0,
    expansionLeft: 0,
    expansionRight: 0,
    expansionRear: 0,
    expansionFrontDisabled: true,
    expansionLeftDisabled: true,
    expansionRightDisabled: true,
    expansionRearDisabled: true,
    sensorFrontX: 0,
    sensorFrontY: 0,
    sensorFrontDisabled: true,
    sensorLeftX: 0,
    sensorLeftY: 0,
    sensorLeftDisabled: true,
    sensorRightX: 0,
    sensorRightY: 0,
    sensorRightDisabled: true,
    sensorRearX: 0,
    sensorRearY: 0,
    sensorRearDisabled: true,

    updateHz: 100,
    latencyMs: 25,
    latencyDisabled: true,
}
